name: Rename and Deploy Site

on:
  push:
    branches:
      - main

jobs:

  rename-project:
    if: ${{ github.repository != 'fastn-stack/fastn-template' && github.event.created }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Rename the project
        run: |
          sed -i -e "s/<user_name>/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/g" \
            -e "s/<repo_name>/$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')/g" \
            FASTN.ftd FASTN/ds.ftd index.ftd sidebar.ftd README.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          push_options: --force

  build:
    needs: rename-project
    if: ${{ github.repository != 'fastn-stack/fastn-template' && always() && !failure() && !cancelled() }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull the latest commits
        run: git pull
      - run: source <(curl -fsSL https://fastn.com/install.sh)
      - name: Build the pages with fastn
        run: |
          echo "Using '$CI_REPOSITORY_NAME_SLUG/' as the base while building"
          fastn build --base=/$CI_REPOSITORY_NAME/
      - name: copy CNAME if found
        run: '(test -f CNAME && cp CNAME .build) || echo "CNAME does not exist, skipping step"'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build
